### ISSUE TITLE
xrange and python3

### ISSUE THREAD

**Issue by ivanpricewaycom** [SalesforceFoundation/salesforce-streaming-client#1]
Hi there,

replacing "xrange" with "range" is the only fix to make this python3 compatible (line 113).

cheers and thanks for the module, works great.

-ivan

**Comment by adamlincoln** [comment]
@ivanpricewaycom I just pushed version 0.1.3, which should bring full python3 compatibility.  If you see anything broken, please let me know on a new issue.  Thanks!
