### ISSUE TITLE
403::Organization concurrent user limit exceeded

### ISSUE THREAD

**Issue by rmohamedfazil** [SalesforceFoundation/salesforce-streaming-client#15]
I wanted to stream the client continuously. Maximum 20 client run cocncurrently in salesforcestreaming after that we got an error like this 403::Organization concurrent user limit exceeded . I am running One client concurrently but after sometime, I got an error like this ..
[aiocometd.exceptions.ServerError: ('Connection closed by the server', {'ext': {'sfdc': {'failureReason': '403::Organization concurrent user limit exceeded'}, 'replay': True, 'payload.format': True}, 'advice': {'reconnect': 'none'}, 'channel': '/meta/handshake', 'id': '1', 'error': '403::Handshake denied', 'successful': False}) ] . 
I don't know why this error coming Can you give some solution about this issue?

**Comment by tonimelisma** [comment]
That's not a bug or issue with the Python library, that's just a limitation of the Salesforce licence you have subscribed to. If you upgrade to Enterprise Edition you can raise the limit from 20 to up to 1,000 simultaneous concurrent subscribes and with Performance and Ultimate Editions you are permitted up to 2,000. If you don't see the need to upgrade the licence, you can also consult with your Account Executive and inquire if there's an option to purchase more simultaneous subscriber licences.
