### ISSUE TITLE
Update to underlying library causes session creation to fail.

### ISSUE THREAD

**Issue by Br4nd0R** [SalesforceFoundation/salesforce-streaming-client#17]
`pip list` output of packages where instantiating SalesforceOAuth2Session was failing:

certifi                      2018.11.29
chardet                      3.0.4
Click                        7.0
idna                         2.8
oauthlib                     3.0.1
pip                          19.0.2
psycopg2-binary              2.7.7
requests                     2.21.0
requests-oauthlib            1.2.0
salesforce-requests-oauthlib 0.1.11
setuptools                   40.6.3
six                          1.12.0
urllib3                      1.24.1

**Comment by adamlincoln** [comment]
example of working virtualenv `pip list`:

asn1crypto (0.24.0)
certifi (2018.4.16)
cffi (1.11.5)
chardet (3.0.4)
click (6.7)
cryptography (2.2.2)
idna (2.7)
oauthlib (2.1.0)
pip (9.0.1)
pycparser (2.18)
requests (2.19.1)
requests-oauthlib (1.0.0)
salesforce-requests-oauthlib (0.1.4)
setuptools (28.8.0)
six (1.11.0)
urllib3 (1.23)

**Comment by adamlincoln** [comment]
Closed via https://github.com/SalesforceFoundation/salesforce-requests-oauthlib/pull/19
