### ISSUE TITLE
Change Data Capture

### ISSUE THREAD

**Issue by Vanderstok** [SalesforceFoundation/salesforce-streaming-client#18]
Looking through the code it looks like that Change Data Capture events (/data/ are not supported?
 
    def subscribe(self, channel, callback, replay=True, autocreate=True):
        type = None
        if channel.startswith('/u/'):
            type = 'generic'
        elif channel.startswith('/topic/'):
            type = 'push_topic'
        elif channel.startswith('/event/'):
            type = 'event'
        else:
            raise BadSubscriptionException(
                '{0} is not a valid subscription channel.'.format(
                    channel
                )
            )

**Comment by adamlincoln** [comment]
@Vanderstok fix in progress

**Comment by adamlincoln** [comment]
@Vanderstok fixed in https://github.com/SalesforceFoundation/salesforce-streaming-client/commit/c1e0b85e7e7d18d046cdd94422564b36abb65369 and released to pypi as version 0.1.13

Please let me know if it doesn't work for you!
