### ISSUE TITLE
Error with 0.1.2

### ISSUE THREAD

**Issue by christophe-gabard** [SalesforceFoundation/salesforce-streaming-client#4]
Hello,

I would like to do a PR for Python3 support (mainly a `xrange` to `range` and some `iteritems`stuff) but I just found that we use the 0.1.1 version. I tried the 0.1.2 but it does not work for us.

Our error is on this line : https://github.com/SalesforceFoundation/salesforce-streaming-client/commit/50614edec711e2034d5e2b39f8fc31b7b0a6a625#diff-15c82b19be1100d35139cde27c69f4ccR233

Objects that we received from SF does not have a `payload` key, only `event`, `sobject` and `channel`.

I'm not sure why you made this change, can we found a way to have the lib work for us, too ? Let me know if I can do something.

Thanks for all.

**Comment by adamlincoln** [comment]
Hi @christophe-gabard - I was hasty with a release to enable platform events, and broke push topics.  This should be fixed in release 0.1.3, which is now in pypi.

Thanks for the report!

**Comment by christophe-gabard** [comment]
Thank you for the release !

**Comment by christophe-gabard** [comment]
Hi,
@adamlincoln made Python3 compatibility commit in the previous release. I have tested it on Python 3.6 and all seems work with the last release !
