### ISSUE TITLE
Callback url limitation

### ISSUE THREAD

**Issue by hossein761** [SalesforceFoundation/salesforce-streaming-client#6]
```python
self.callback_url = 'https://{0}:{1}'.format(
            self.local_server_settings[0],
            str(self.local_server_settings[1])
        )

```
in salesforce_requ:ests_oauthlib has stricted the callback url to have the `https://domain:port` format. so urls like `https://localhost:4444/oauth/_callback` are not possible?

**Comment by adamlincoln** [comment]
@hossein761 in https://github.com/SalesforceFoundation/salesforce-requests-oauthlib/commit/2683cb8e2a0e561644e1d84b41737bb3b6d8077e I updated this section of salesforce_requests_oauthlib to properly handle non-standard ports.  It should also be clearer now that any url path you want is supported.  (I often use urls like your example!)  If you try something and it doesn't work, please file a new issue or follow up here.
